### ISSUE TITLE
Integrity check always fails for nitropad-t430-v1.4.npf

### ISSUE THREAD

**Issue by tlikonen** [Nitrokey/heads#12]
When trying to flash [nitropad-t430-v1.4.npf](https://github.com/Nitrokey/heads/releases/download/v1.4/nitropad-t430-v1.4.npf) the integrity check always fails. I have manually checked the SHA256 sums of the said `.npf` file itself and its internal `.rom` file. Both verify correctly. So I have had to `unzip` the `.npf` file and use `.rom` file for flashing. That worked.

First I tried to flash `.npf` file with rom version 1.3.1. Later I had rom version 1.4 and tried the flashing again: the automatic file integrity check always fails.

**Comment by marmarek** [comment]
Same here. It seems [create-npf.sh](https://github.com/Nitrokey/heads/commit/85ca2dfa249981a1d5ee6a0f50ff02875c25a194#diff-cc53a2ccac5c32407bf1c3b4eaa525555a0cfbcae540f9293bc3e43aa33a5630) script includes `sha256sum` file, while `flash-gui.sh` expects `sha256sum.txt`.
Furthermore, `sha256sum -cs` call in `flash-gui.sh` is called in a wrong directory, so it has no chance to find file extracted into `/tmp/verified_rom`...

cc @daringer

**Comment by szszszsz** [comment]
Thank you for checking that!

@daringer It should suffice then to rebuild the npf archive with the proper hash file naming

**Comment by marmarek** [comment]
> @daringer It should suffice then to rebuild/repack the npf archive with the proper hash file naming

It may work if you include full path (including `/tmp/verified_rom/`) too. But I think that's something worth fixing anyway.

BTW, it might be a good idea to include `sha256sum.txt.sig` there too, and verify the signature first. But that's separate feature.

**Comment by tlaurion** [comment]
I would like to hijack this issue for a second for important considerations. Heads is not reproducible for a while now, and I would love to see more collaboration into fixing them (fixing the cause) instead of distributing signed binaries from forks of the main project.

Ideally, the ROMs produced by CIs should produce the exact same ROM.
Those ROMs, being produced from multiple untrusted sources, should produce the same ROMs for the same upstream commits.

If we (Insurgo, Nitrokey, Purism) would collaborate into fixing reproducibility issues, then the ROMs should be the same, produced locally by users then the one downloaded elsewhere.

The modules to work on, which are not reproducible, are listed here:


Once that is resolved, the next step would be to create tags and releases, on which final hashes should be given.

Of course, signing those is a plus to attest to end user that we recognise and reviewed the changes that were applied upstream and in our branches up to that point.

But signing non reproducible builds not only diverge from Heads original mission, divide efforts of maintainer ship that should be happening upstream, but also bring users to our own documentation and guides instead of bonifying upstream one.

**Comment by szszszsz** [comment]
@daringer Can you let us know, if the binary is updated?

**Comment by daringer** [comment]
updated create-npf.sh, replaced the files (`.npf` inside the release) should work now...

**Comment by nord73** [comment]
The checksum for the file sha256 is still wrong and fails the sha256 verification with:
`sha256sum: FAILED`
`sha256sum: WARNING 1 of 9 computed checksums did NOT match`
Then the ROM Integrity Check also fails with:
`/media/nitropad-x230-v1.4-npf integrity check failed. Did not flash.`

**Comment by marmarek** [comment]
> Furthermore, `sha256sum -cs` call in `flash-gui.sh` is called in a wrong directory, so it has no chance to find file extracted into `/tmp/verified_rom`...

I believe this is still the case.

**Comment by daringer** [comment]
okok, this calls for a new release ...

**Comment by daringer** [comment]
updated the release, should work now(tm) ... sorry for the inconvenience, just updated the npf build process, no actual changes inside the firmware, thus no new release, confirmed and tested here, can someone else retest?

**Comment by szszszsz** [comment]
AFAIK this was tested at Nitrokey. Closing as fixed.
